steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/plogg-vn/cloud-run-source-deploy/demo-nuxt3/dat-demo-project', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/plogg-vn/cloud-run-source-deploy/demo-nuxt3/dat-demo-project']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'SERVICE-NAME', '--image', 'us-central1-docker.pkg.dev/plogg-vn/cloud-run-source-deploy/demo-nuxt3/dat-demo-project', '--region', 'us-central1']
images:
- us-central1-docker.pkg.dev/plogg-vn/cloud-run-source-deploy/demo-nuxt3/dat-demo-project